<?php


// breadcrums
echo '<div class="panelBorder panelShadow invertedPanelColor panel panelLeft">';
    echo '<div ';
        echo ' class="panelText"';
    echo ' >';            
        echo 'Tot onze spijt is er iets mis gegaan.' . '<br />';
        echo 'De pagina die u zoekt is niet gevonden.' . '<br />';
        echo 'Er is een melding van gemaakt en we zullen proberen het probleem op te lossen.' . '<br />';
    echo '</div>';
    echo '<div ';
        echo ' class="panelTitle"';
        echo ' >';
        echo 'The page you are looking for has not been found.';
    echo '</div>';
    echo '<div ';
        echo ' class="panelText"';
    echo ' >';            
        echo 'To our regret, something has gone wrong..' . '<br />';
        echo 'The page you requested was not found.' . '<br />';
        echo 'We created a notification of this problem, and we will try to solve it.' . '<br />';
    echo '</div>';
echo '</div>';    
