<?php

/* 
 *  Project: MbAdmin
 * 
 *  File: /view/MbAdmin/index.phtml
 * 
 * Last revision: 16-01-2017
 * 
 * Purpose: 
 *      this file constructs basic content for the pages 
 * 
 *  Author: Pleisterman
 *  Web: www.pleisterman.nl 
 *  Mail: info@pleisterman.nl 
 *  GitHub: Pleisterman 
 * 
 *  Copyright (C) 2017 Pleisterman 
 *  GNU General Public License 3+ 
 *  see <http://www.gnu.org/licenses/>
 * 
 *  Zend Framework (http://framework.zend.com/)
 *
 *  @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 *  @license   http://framework.zend.com/license/new-bsd New BSD License
 */

?>

<script>
    // add onload event    
    window.onload = function(){
        // language
        pleisterman.selectedLanguageId = <?php echo $selectedLanguageId; ?>; 
        pleisterman.languages = <?php echo $languages; ?> 
        // done language

        // translations     
        pleisterman.translations = <?php echo $translations; ?> 
        // done translations

        // add base directory
        pleisterman.baseDirectory = '<?php echo $baseDirectory; ?>'; 
        // add work directory
        pleisterman.workDirectory = '<?php echo $workDirectory; ?>'; 
        // add options
        pleisterman.options = <?php echo $options; ?> 
        // add colors
        pleisterman.colors = <?php echo $colors; ?> 
        // add languages
        pleisterman.languages = <?php echo $languages; ?> 
        // add elp subjects
        pleisterman.helpSubjects = <?php echo $helpSubjects; ?> 
        // add token
        pleisterman.token = '<?php echo $token; ?>';
        // add password reset
        pleisterman.isResetPassword = '<?php echo $isResetPassword; ?>';
        // add rememberMe option
        pleisterman.rememberMe = <?php echo $rememberMe; ?>; 
        // add minimum password strength
        pleisterman.minimumPasswordStrength = <?php echo $minimumPasswordStrength; ?>; 
        // add minimum password length
        pleisterman.minimumPasswordLength = <?php echo $minimumPasswordLength; ?>; 
        // add minimum login name length
        pleisterman.minimumLoginNameLength = <?php echo $minimumLoginNameLength; ?>; 
        // add page token refrsh period
        pleisterman.pageTokenRefreshPeriod = <?php echo $pageTokenRefreshPeriod; ?>; 

        // start the application
        pleisterman.start();

    };
    // done add onload event    
</script>