<?php
/* 
 *  Project: MiniBuilder Admin
 * 
 *  File: NoUserController.php
 * 
 *  Last Revision:  24-11-2016
 * 
 *  Author: Sharesoft
 *  Web: www.sharesoft.nl 
 *  Mail: info@sharesoft.nl 
 *  GitHub: SharesoftNL 
 * 
 * Purpose: this file adds: inline javascript with variables: languageMenus and selectedLanguageMenu,
 *                          padding to the content of the html
 * 
 *  Copyright (C) 2016 Sharesoft 
 *  GNU General Public License 3+ 
 *  see <http://www.gnu.org/licenses/>
 * 
 *  Zend Framework (http://framework.zend.com/)
 *
 *  @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 *  @license   http://framework.zend.com/license/new-bsd New BSD License
 */


echo $pageHtml;
