<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Common\Service\Database\DataController'               => __DIR__ . '/src/Common/Service/Database/DataController.php',
  'Common\Service\Database\MySql\MySqlDataBaseAdapter'   => __DIR__ . '/src/Common/Service/Database/MySql/MySqlDataBaseAdapter.php',
  'Common\Service\Database\MySql\MySqlDataController'    => __DIR__ . '/src/Common/Service/Database/MySql/MySqlDataController.php',
  'Common\Service\Database\MySql\MySqlParser'            => __DIR__ . '/src/Common/Service/Database/MySql/MySqlParser.php',
  'Common\Service\Database\Sqlite\SqliteDataBaseAdapter' => __DIR__ . '/src/Common/Service/Database/Sqlite/SqliteDataBaseAdapter.php',
  'Common\Service\Database\Sqlite\SqliteDataController'  => __DIR__ . '/src/Common/Service/Database/Sqlite/SqliteDataController.php',
  'Common\Service\Database\Sqlite\SqliteParser'          => __DIR__ . '/src/Common/Service/Database/Sqlite/SqliteParser.php',
  'Common\Service\Debugger'                              => __DIR__ . '/src/Common/Service/Debugger.php',
  'Common\Service\DeviceDetector'                        => __DIR__ . '/src/Common/Service/DeviceDetector.php',
  'Common\Service\LanguageController'                    => __DIR__ . '/src/Common/Service/LanguageController.php',
  'Common\Service\MobileDetect'                          => __DIR__ . '/src/Common/Service/MobileDetect.php',
  'Common\Service\SessionController'                     => __DIR__ . '/src/Common/Service/SessionController.php',
  'Common\Service\SqlLiteDatabase'                       => __DIR__ . '/src/Common/Service/SqlLiteDatabase.php',
);
